### ISSUE TITLE
opsim should simulate transactions on pending block not latest

### ISSUE THREAD

**Issue by jakim929** [ethereum-optimism/supersim#118]
to more closely mirror sequencer behavior, we should be simulating interop tx WHILE building the block. The block builder should apply those changes on the "pending" block.

Meaning the debug_traceCall should happen at "pending" block, not "latest".

few considerations here
1. do we want to add a custom delay to replicate a chain's willingness to accept message at "safe" "cross-unsafe" etc. - in that case for those should have custom intervals
2. debug_traceCall on anvil doesn't support block overrides yet - this is one way to do timestamp / block checks on pending
3. we should check if "pending" tag works when calling debug_traceCall

**Comment by roninjin10** [comment]
Can confirm 'pending' should work on debug_traceCall for all rpcs.

Adding block override support to anvil debug_traceCall would be a pretty tiny lift given they do support it for eth_call
