### ISSUE TITLE
Orchestrator: Add commands to stop instances

### ISSUE THREAD

**Issue by fainashalts** [ethereum-optimism/supersim#12]
We'll need a way for users to stop the Orchestrator elegantly. We should offer a command to do this: 

`supersim stop` or `supersim down`

We may also wish to allow users to start or stop individual instances. The flow and need for this is a bit unclear, so this initial task is for stopping all of the instances the orchestrator is running. 

**Definition of Done**
Orchestrator is able to stop all the Anvil instances it is running when given the appropriate command by the user.

**Comment by hamdiallam** [comment]
Closing in favor of simply having it run in the terminal and gracefully shutting down on interrupt (which happens now). Also expected behavior of anvil rn
