### ISSUE TITLE
cli?

### ISSUE THREAD

**Issue by jakim929** [ethereum-optimism/supersim#129]
Need to spec more but it's getting clear some sort of CLI will be useful for dealing with multichain deployments + interact with system contracts/SuperchainERC20

### Candidates for initial use cases
- multichain deployment
- interacting with SuperchainERC20
- interacting with interop contracts CrossL2Inbox
- interacting with other system contracts

**Comment by fainashalts** [comment]
Yes I think you're on the right track here for sure~ would make the multichain experience much more straightforward.

**Comment by jakim929** [comment]
closing since this isn't directly relevant to supersimm
