### ISSUE TITLE
Orchestrator: Add mode selection

### ISSUE THREAD

**Issue by fainashalts** [ethereum-optimism/supersim#13]
Users will have the option to start up supersim in "vanilla" or "forking" mode. This initial task is for adding the `--fork` flag. A future task will take the selection of `--fork` and fork the requested chains. For now, when a user indicates they wish to use `--fork` we should save that information in the orchestrator but still just spin up vanilla chains. 

**Definition of Done**
When a user adds `--fork` upon starting supersim, that information is saved in orchestrator. Though it begins the local instances in vanilla mode, it is now equipped to check whether a user has indicated a desire to use forking mode.

**Comment by hamdiallam** [comment]
Closing in favor of #25
