### ISSUE TITLE
Productize Supersim

### ISSUE THREAD

**Issue by fainashalts** [ethereum-optimism/supersim#131]
Supersim should be installable from the CLI without directly building from source. We have a couple of distribution options that could be good: 

1. Homebrew: users can install Supersim via `brew install`
2. Go Modules: let users install with `go install github.com/ethereum-optimism/supersim`

There are more options like Docker, Github releases with pre-built binaries, etc.

The purpose of this issue is (1) to decide on one or multiple ways for devs to install Supersim from their CLI, and allow them to update the tool witjh `supersimup` and user it with `supersim` and (3) to implement. 

For `supersimup` the expected functionality is as follows:
- Verify if you have anvil installed and potentially run foundryup
- Detect which arch & os the user is running on
- Pull the correct binary based on what arch the user is running from our latest github release https://github.com/ethereum-optimism/supersim/releases
- Add the binary to the users path

**Definition of Done**

- [ ] Users can install Supersim via the chosen distribution method. 
- [ ] Users can use a command like `supersimup` to update and `supersim` to use Supersim in their CLI. 
- [ ] Supersim documentation has been updated to reflect this change.

**Comment by nitaliano** [comment]
For `brew` setup we can update our goreleaser config to also publish to homebrew https://goreleaser.com/customization/homebrew/

For `supersimup` I think the script only needs too
* Verify if you have anvil installed and potentially run foundryup
* Detect which arch & os the user is running on
* Pull the correct binary based on what arch the user is running from our latest github release https://github.com/ethereum-optimism/supersim/releases
* Add the binary to the users path
