### ISSUE TITLE
Add interop delay option

### ISSUE THREAD

**Issue by fainashalts** [ethereum-optimism/supersim#133]
We want users to be able to simulate an interop inclusion delay as some chains may not allow inclusion of messages from an unsafe block. Initially we can set this to a static value of 5 blocks if the features is enabled. For future improvements we can assess more dynamic ways to do this. 

**Definition of Done**
- [ ] Networks can optionally be set to include a 5 second delay in inclusion of an interop message, though the default should not include a delay.

**Comment by tabshaikh** [comment]
@jakim929 started this https://github.com/ethereum-optimism/supersim/pull/255 let me know if i am going in the right direction :)

**Comment by tabshaikh** [comment]
@jakim929 can be closed
