### ISSUE TITLE
refactor SuperchainERC20 event logging in opsim

### ISSUE THREAD

**Issue by jakim929** [ethereum-optimism/supersim#144]
L2NativeSuperchainERC20 and SuperchainWETH logging can use the same code. We'll prob have more token types soon too.

**Comment by s4rv4d** [comment]
Can I work on this ? Is anyone taking this up ?

**Comment by tabshaikh** [comment]
@jakim929 made a pr for the changes

**Comment by s4rv4d** [comment]
@jakim929 @fainashalts can you pls clarify is this issue is still open, i saw there are merged related to SuperchainERC20 event logging on opsimulator, and L2NativeSuperchainERC20 and SuperchainWETH use ICrosschainERC20 for common event emits so is there work required here and what is the scope?

**Comment by tabshaikh** [comment]
@s4rv4d had renamed the pr incorrectly but the pr makes a common logging function for both `L2NativeSuperchainERC20` and `SuperchainWETH` which use `ICrosschainERC20`. so i think this issue is complete

**Comment by tabshaikh** [comment]
@jakim929 can be closed :)
