### ISSUE TITLE
Incorrect SuperchainERC20 address in README (at least when building locally)

### ISSUE THREAD

**Issue by karlfloersch** [ethereum-optimism/supersim#152]
**Bug Description**
The README says the predeployed SuperERC20 address is `0x61a6eF395d217eD7C79e1B84880167a417796172` but when I investigated it seemed to be getting deployed to `0xA301B4dbc64c5BDA1f128186B1D084246E964F13`

**Steps to Reproduce**

**Building and running supersim**

1. `git clone ...supersim...`
2. `just generate-genesis`
3. `just build-go`
4. `just build-contracts`
5. `go build cmd/main.go`
6. `./main --interop.autorelay`
```
$ ./main --interop.autorelay 
INFO [09-18|11:15:27.229] starting supersim
INFO [09-18|11:15:27.401] configuring interop contracts
INFO [09-18|11:15:27.401] starting L2ToL2CrossDomainMessenger autorelayer
INFO [09-18|11:15:27.408] supersim is ready
INFO [09-18|11:15:27.413] 
...
```

**Testing [Example B](https://github.com/ethereum-optimism/supersim?tab=readme-ov-file#example-b-l2-to-l2-send-an-interoperable-superchainerc20-token-from-chain-901-to-902)**

I try to follow the tutorial and run
```
cast send 0x61a6eF395d217eD7C79e1B84880167a417796172 "mint(address _to, uint256 _amount)"  0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266 1000  --rpc-url http://127.0.0.1:9545 --private-key 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
```
However, there is no code at this contract address. Tested this with:
```
cast code 0x61a6eF395d217eD7C79e1B84880167a417796172 --rpc-url http://127.0.0.1:9546
0x
```

But when I use `cast send 0xA301B4dbc64c5BDA1f128186B1D084246E964F13 ...` the tutorial works as expected.

**Expected behavior**
Expected the tutorial to work!

**Environment Information:**
 - Operating System: OSX
 - Package Version daa397a6b2058b2001ad49b7502a4ebcbe08a260

**Additional context**
I would love to have a section in the readme on building & running Supersim locally. It used to have that info but it got removed recently it seems.

---

⚠️ **Notice:** Issues that do not include the following sections will be subject to closure:
- Bug Description
- Steps to Reproduce
- Environment Information

Please ensure all required sections are filled out accurately to expedite the debugging process and improve issue resolution efficiency.

**Comment by jakim929** [comment]
thx for reporting! put out a fix here https://github.com/ethereum-optimism/supersim/pull/153 and also an issue for longer term issue. https://github.com/ethereum-optimism/supersim/issues/154

also added back how to build / run
