### ISSUE TITLE
Bug: example B doesn't seem to work

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/supersim#157]
**Bug Description**
I'm running through example B in the README and nothing really happens. I get a bug trying to get the ERC20 balance after.

```
cast balance --erc20 0x0bEa8920a4FfB1888Ec3Ac1BC0D23f414B0a28cA 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266 --rpc-url http://127.0.0.1:9546
Error: 
buffer overrun while deserializing
```

**Steps to Reproduce**

1. Follow tutorial B
2. Log in step 4 never appears
3. Try to run step 5 and get an error.

**Expected behavior**
Example works as described.

**Comment by jakim929** [comment]
thanks for the report! can you try with the latest release? https://github.com/ethereum-optimism/supersim/releases/tag/0.1.0-alpha.4

i think https://github.com/ethereum-optimism/supersim/pull/153 this should fix this

**Comment by jakim929** [comment]
should be fixed now
