### ISSUE TITLE
Brew version is untagged

### ISSUE THREAD

**Issue by fainashalts** [ethereum-optimism/supersim#192]
Looks like based on https://github.com/ethereum-optimism/supersim/issues/179 the Supersim version is not actually tagged.

**Comment by jakim929** [comment]
confirmed it is fixed with https://github.com/ethereum-optimism/supersim/pull/199

```
> supersim --version
supersim version 0.1.0-alpha.17 (edf48a6e25b245e1a9848d21a3224caec83851f7) built at 2024-10-15T21:13:19Z
```
