### ISSUE TITLE
Temp logging not working

### ISSUE THREAD

**Issue by tremarkley** [ethereum-optimism/supersim#205]
While supersim is running, the temp logs specified in the terminal do not exist.

Steps to reproduce:
1. Start supersim
2. Try to navigate to one of the log files that is specified in the terminal

Expected behavior:
Opening the log file specified in the terminal should show the logs for that chain

Actual behavior:
The log file at that path is not found

Workaround: 
Run supersim specifying a log path: `supersim --logs.directory "/tremarkley/supersim" `

**Comment by s29papi** [comment]
Hi @jakim929, I would like to take this one ( work on this )
