### ISSUE TITLE
Add CLI command to display interop spec & optimism docs in Supersim flow

### ISSUE THREAD

**Issue by fainashalts** [ethereum-optimism/supersim#227]
When a user runs `supersim --docs` they should get a list of the following clickable links:

[Superchain Interop Specs](https://specs.optimism.io/interop/overview.html)
[Optimism Documentation](https://docs.optimism.io/)
[Supersim Documentation](https://supersim.pages.dev/)

**Comment by jameskim0987** [comment]
I can have a look at this one!
