### ISSUE TITLE
Allow customizing anvil hosts

### ISSUE THREAD

**Issue by jakim929** [ethereum-optimism/supersim#262]
context: https://github.com/ethereum-optimism/supersim/issues/250

- add a string CLI flag `--host`
- by default this should be unset or set to `127.0.0.1`
- add a `Host` parameter to ChainConfig
- anvil.go should pass the host specified in the config when starting anvil
- admin server should also use the same host
- add unit tests to make sure this works correctly

**Comment by s29papi** [comment]
Hi! @jakim929  I'd like to work on this issue.
