### ISSUE TITLE
recommendations for error management and user experience

### ISSUE THREAD

**Issue by hamzahaluk** [ethereum-optimism/supersim#270]
My suggestions to improve the user experience and make error management more robust and to create a more readable and maintainable codebase:
1. Error Management
If the RPC client fails to connect in theStart function, the error is logged directly and displayed to the user:

`if err := a.cmd.Start(); err != nil {
    return fmt.Errorf("Anvil not initialized: %w", err)
}
`

2. Log Management
Added logging inremoveFile function:

`func (a *Anvil) removeFile(file *os.File) {
    if err := os.Remove(file.Name()); err != nil {
        a.log.Warn("Temporary file could not be deleted", "file.path", file.Name(), "err", err)
    }
}
`
3. SimulatedLogs Improvement
Added a condition to check for empty callFrame states:

`if result.Calls == nil {
    return nil, errors.New("No calls were made during the simulation")
}
`

Tested Environment
Go Version: 1.20+
Anvil Version: v0.2.5

Related Issues
This PR resolves or addresses the following GitHub issues:
#123: “Error creating log file.”
#124: “Missing data in simulation logs.”

**Comment by jakim929** [comment]
Thank you for opening the issue! I think these changes are already implemented, so closing for now. Feel free to re-open with repros if you think the issue still exists.

1 is already implemented https://github.com/ethereum-optimism/supersim/blob/dfd93559553d04391167db06197f74d7f58860ef/anvil/anvil.go#L193-L195

2 is already implemented https://github.com/ethereum-optimism/supersim/blob/dfd93559553d04391167db06197f74d7f58860ef/anvil/anvil.go#L333-L335

3 should not error out - i think it's possible for the callframe to be empty (tx reverted) for instance
