### ISSUE TITLE
TicTacToe frontend uses a hardcoded address

### ISSUE THREAD

**Issue by tabshaikh** [ethereum-optimism/supersim#274]
**Describe the bug**
as the ticTacToe frontend uses a hardcoded address, there is a blank page if create2 contract address is different

**Comment by fainashalts** [comment]
Thanks for raising this @tabshaikh and I see you made a PR to fix! 🤩 Looks like this is resolved so I'm going to close but if I'm missing something comment here and I'll reopen.
