### ISSUE TITLE
Orchestrator: User command to display instance information in CLI

### ISSUE THREAD

**Issue by fainashalts** [ethereum-optimism/supersim#9]
As users develop with supersim, they will need to pull up information about their local nodes from time to time. We should create a command for that purpose, something like:

`supersim get nodes` or `supersim info`

** Definition of Done**
Using a single command, the user can view information about the nodes they have running, specifically at least: 
1. All instances running
2. A process identifier for each
3. The port of each instance

** Stretch goal:** Attempt to identify other useful information this command could display.

**Comment by hamdiallam** [comment]
Close in favor of #10
