### ISSUE TITLE
Some deployment scripts do not work with supersim

### ISSUE THREAD

**Issue by tremarkley** [ethereum-optimism/supersim#91]
Hyperlane attempted to run one of their deployment scripts against supersim and it failed (https://discord.com/channels/1244729134312198194/1255653436079210496/1270498688065605742):

nambrot: On a different note, I just tried to deploy Hyperlane contracts on supersim to create a prototype for relaying with supersim, but running into a pretty odd issue. Specifically, I can't seem to deploy multiple contracts, the first one will succeed, but then all subsequent ones will fail:
```
➜  solidity git:(nambrot/support-fallback-routing-in-sdk-metadata-builder) ✗ forge create StaticAggregationIsmFactory --private-key $PKEY
[⠊] Compiling...
[⠢] Compiling 12 files with Solc 0.8.22
[⠆] Solc 0.8.22 finished in 132.20ms
Compiler run successful!
Deployer: 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
Deployed to: 0x5FbDB2315678afecb367f032d93F642f64180aa3
Transaction hash: 0x381c9b4f6751f7b1525139e1d1b64c3f612bc25c985c043f3148abe97db530b4
➜  solidity git:(nambrot/support-fallback-routing-in-sdk-metadata-builder) ✗ forge create StaticAggregationIsmFactory --private-key 
[⠊] Compiling...
No files changed, compilation skipped
Error: 
server returned an error response: error code -32603: EVM error CreateCollision
```
With a vanilla anvil node it does work:
```
➜  solidity git:(nambrot/support-fallback-routing-in-sdk-metadata-builder) ✗ forge create StaticAggregationIsmFactory --private-key 
[⠊] Compiling...
No files changed, compilation skipped
Deployer: 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
Deployed to: 0x5FbDB2315678afecb367f032d93F642f64180aa3
Transaction hash: 0xd7b62cab156771470cc146aeb8b17232fbdda7a52d7a5639bb408c955c782ade
➜  solidity git:(nambrot/support-fallback-routing-in-sdk-metadata-builder) ✗ forge create StaticAggregationIsmFactory --private-key 
[⠊] Compiling...
No files changed, compilation skipped
Deployer: 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
Deployed to: 0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512
Transaction hash: 0x0638d1f0d6af915a7ee79c274d8114d0d1a238d57e4d340955a40e4301d3fd0a
```

tynes: EVM error CreateCollision its prob a nonce thing
that means there is already bytecode at the account that its trying to deploy to
so if you script uses create2 thats prob it, since the code already exists
there should be a cheatcode or something vm.deployIfNotExists()
otherwise you need to do the create2 calculation in solidity and then do if (addy.code.length != 0) continue; "do deployment"

nambrot: That's what I first thought to, but I'm not using Create2
this is a vanilla forge create command (which presumably just uses CREATE)
and it does work with a vanilla anvil node i'm starting up as comparison
With both setups, the nonce does increase as expected

Matt Solomon: This is because the deployer of 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266 is an anvil default test account with a publicly known private key, so the contract addresses it deploys to with each subsequent nonce probably have code on some networks at some addresses, hence the CreateCollison

nambrot: So this is off the supersim anvil nodes, but this did help me confirm that somehow there is existing contract state at the nonce 1 contract address of 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266. However the nonce is 0 for that key (since I'm not forking). However I did notice that the genesis block likely contains these overrides at 0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512 https://github.com/ethereum-optimism/supersim/blob/f0ef708507b521b2046b6a7646fd60a82301e167/genesis/generated/l1-allocs/901-l1-allocs.json#L1. I'm assuming y'all have a bunch of system contracts that you set this way, but I would probably recommend to set them on different addresses so that supersim users who will naturally choose the default key won't run into this

tynes: This is likely a bug in genesis generation, I wonder if this nonce is being set in fresh L2 genesis states

nambrot: would hypothesize that you do use that key for genesis generation, but the nonce itsn't getting set in the genesis block?

proto: I believe the deployer on L1 dev genesis is a default account. And the deployed contracts would all have addresses that depend on this test deployer account and nonce. The deployer test script contract itself should wipe itself as part of the Allocs L1 output routine. Somewhere in there it also sets the pre funded accounts. And in either routine it might end up with the nonce reset. And this is the L1 dev genesis, separate from the L2 genesis (of which I believe we do check the number of generated L2 accounts matches the expectations and excludes scripts and such)

nambrot: fwiw i ran into this issue on the l1 dev chain

**Comment by jakim929** [comment]
in L1 genesis, the dev account is used to deploy using CREATE all proxies + SafeSingleton + SafeProxyFactory. Means the 

However, the nonce increment isn't captured in the state dump in foundry, since it skips persisting account slots for the sender of the forge script.
see 
https://github.com/foundry-rs/foundry/blob/1197fbea0b0f9dde45579a61a5ff956fc0aee426/crates/cheatcodes/src/evm.rs#L134

some options
- manually bump the nonces in the allocs for the dev accounts. this can become brittle as the number of contracts deployed using CREATE increases.
- use a fresh set of dev accounts to deploy each chain <= easiest
- update the deploy script in the monorepo to use CREATE2
